apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-gitea-postgresql-0
  namespace: gitea
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: postgresql
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

